[data]
    email    = "k@bk.bio"
    workmail = "Bhargav.Kantheti@cbre.com"
    name     = "Bhargav Kantheti"

[git]
    autoAdd = true
    autoCommit = true
    autoPush = true
    commitMessageTemplate = "SYSCHORE SYNC"

[edit]
    command = "zed"
